@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package me.theabab2333.harvestheritage.datagen.recipe;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;