license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "theabab2333, Abslb, GTriXy"
logoFile = "harvestheritage_logo_512.png"
description = '''
A simple hybridization mod... trying to imitate IC2's hybridization....
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
