@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package me.theabab2333.harvestheritage.datagen.loot;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;